In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("적용유형별_가중합_상위10.csv", encoding="utf-8-sig")
data.head()

             address  cluster   적용유형     가중합점수  농업_지원  농업_매물  교통  교육  편의  서비스
0      경상북도 영주시 하망동         0  가족정착형  2.193685      6     10   6  10  10   10
1      경상북도 상주시 냉림동         0  가족정착형  2.193339      8     10  10  10  10   10
2      경상북도 영주시 영주동         0  가족정착형  2.153575      6      9   7  10  10   10
3      경상북도 영주시 휴천동         0  가족정착형  2.143976      6      9   7  10  10   10
4  전라북도 전주덕진구 호성동1가         0  가족정착형  2.119683     10      9  10  10  10   10

# 그래프표시용 데이터 수정

In [3]:
data.columns

Index(['address', 'cluster', '적용유형', '가중합점수', '농업_지원', '농업_매물', '교통', '교육',
       '편의', '서비스'],
      dtype='object')

In [4]:
avg_columns = ['농업_지원', '농업_매물', '교통', '교육', '편의', '서비스']
temp = pd.DataFrame()
for col in avg_columns:
    temp_copy = data[["address","적용유형"]].copy()
    temp_copy['시설유형'] = col
    temp = pd.concat([temp, temp_copy], ignore_index=True)
temp=temp.sort_values(by=["address","적용유형","시설유형"]).reset_index(drop=True)

In [5]:
temp["점수"]=pd.NA
temp.head()

         address   적용유형   시설유형    점수
0  경상북도 경주시 노동동   영농상속형     교육  <NA>
1  경상북도 경주시 노동동   영농상속형     교통  <NA>
2  경상북도 경주시 노동동   영농상속형  농업_매물  <NA>
3  경상북도 경주시 노동동   영농상속형  농업_지원  <NA>
4  경상북도 경주시 노동동   영농상속형    서비스  <NA>

In [13]:
for i, j, k in zip(temp["address"], temp["적용유형"], temp["시설유형"]):
    temp.loc[(temp["address"]==i)&(temp["적용유형"]==j)&(temp["시설유형"]==k), "점수"] = data.loc[(data["address"]==i)&(data["적용유형"]==j), k].values[0]

In [ ]:
temp.to_csv("행정코드매칭데이터.csv", encoding="utf-8-sig", index=False)